/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AApp: typeof import('antdv-next')['App']
    AAvatar: typeof import('antdv-next')['Avatar']
    AButton: typeof import('antdv-next')['Button']
    ACard: typeof import('antdv-next')['Card']
    AConfigProvider: typeof import('antdv-next')['ConfigProvider']
    ADrawer: typeof import('antdv-next')['Drawer']
    ADropdown: typeof import('antdv-next')['Dropdown']
    AMenu: typeof import('antdv-next')['Menu']
    ASpace: typeof import('antdv-next')['Space']
    ATag: typeof import('antdv-next')['Tag']
    ATypographyLink: typeof import('antdv-next')['TypographyLink']
    ATypographyText: typeof import('antdv-next')['TypographyText']
    ATypographyTitle: typeof import('antdv-next')['TypographyTitle']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const AApp: typeof import('antdv-next')['App']
  const AAvatar: typeof import('antdv-next')['Avatar']
  const AButton: typeof import('antdv-next')['Button']
  const ACard: typeof import('antdv-next')['Card']
  const AConfigProvider: typeof import('antdv-next')['ConfigProvider']
  const ADrawer: typeof import('antdv-next')['Drawer']
  const ADropdown: typeof import('antdv-next')['Dropdown']
  const AMenu: typeof import('antdv-next')['Menu']
  const ASpace: typeof import('antdv-next')['Space']
  const ATag: typeof import('antdv-next')['Tag']
  const ATypographyLink: typeof import('antdv-next')['TypographyLink']
  const ATypographyText: typeof import('antdv-next')['TypographyText']
  const ATypographyTitle: typeof import('antdv-next')['TypographyTitle']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}